<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CalendrierJoursSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('calendrierjours')->insert([
            [
                'id'=> 1,

                'LundiP1'=> true,
                'LundiP2'=> true,
                'LundiP3'=> true,
                'LundiP4'=> true,
                'LundiP5'=> true,
                'LundiP6'=> true,
                'LundiP7'=> true,
                'LundiP8'=> true,
                'LundiP9'=> true,
                'LundiP10'=> true,

                'MardiP1'=> true,
                'MardiP2'=> true,
                'MardiP3'=> true,
                'MardiP4'=> true,
                'MardiP5'=> true,
                'MardiP6'=> true,
                'MardiP7'=> true,
                'MardiP8'=> true,
                'MardiP9'=> true,
                'MardiP10'=> true,

                'MercrediP1'=> true,
                'MercrediP2'=> true,
                'MercrediP3'=> true,
                'MercrediP4'=> true,
                'MercrediP5'=> true,
                'MercrediP6'=> true,
                'MercrediP7'=> true,
                'MercrediP8'=> true,
                'MercrediP9'=> true,
                'MercrediP10'=> true,

                'JeudiP1'=> true,
                'JeudiP2'=> true,
                'JeudiP3'=> true,
                'JeudiP4'=> true,
                'JeudiP5'=> true,
                'JeudiP6'=> true,
                'JeudiP7'=> true,
                'JeudiP8'=> true,
                'JeudiP9'=> true,
                'JeudiP10'=> true,
                
                'VendrediP1'=> true,
                'VendrediP2'=> true,
                'VendrediP3'=> true,
                'VendrediP4'=> true,
                'VendrediP5'=> true,
                'VendrediP6'=> true,
                'VendrediP7'=> true,
                'VendrediP8'=> true,
                'VendrediP9'=> true,
                'VendrediP10'=> true,
            ],
            [
                'id'=> 2,
                'LundiP1'=> false,
                'LundiP2'=> false,
                'LundiP3'=> false,
                'LundiP4'=> false,
                'LundiP5'=> false,
                'LundiP6'=> false,
                'LundiP7'=> false,
                'LundiP8'=> false,
                'LundiP9'=> false,
                'LundiP10'=> false,

                'MardiP1'=> false,
                'MardiP2'=> false,
                'MardiP3'=> false,
                'MardiP4'=> false,
                'MardiP5'=> false,
                'MardiP6'=> false,
                'MardiP7'=> false,
                'MardiP8'=> false,
                'MardiP9'=> false,
                'MardiP10'=> false,

                'MercrediP1'=> false,
                'MercrediP2'=> false,
                'MercrediP3'=> false,
                'MercrediP4'=> false,
                'MercrediP5'=> false,
                'MercrediP6'=> false,
                'MercrediP7'=> false,
                'MercrediP8'=> false,
                'MercrediP9'=> false,
                'MercrediP10'=> false,

                'JeudiP1'=> false,
                'JeudiP2'=> false,
                'JeudiP3'=> false,
                'JeudiP4'=> false,
                'JeudiP5'=> false,
                'JeudiP6'=> false,
                'JeudiP7'=> false,
                'JeudiP8'=> false,
                'JeudiP9'=> false,
                'JeudiP10'=> false,
                
                'VendrediP1'=> false,
                'VendrediP2'=> false,
                'VendrediP3'=> false,
                'VendrediP4'=> false,
                'VendrediP5'=> false,
                'VendrediP6'=> false,
                'VendrediP7'=> false,
                'VendrediP8'=> false,
                'VendrediP9'=> false,
                'VendrediP10'=> false,
            ],
            [
                'id'=> 3,
                'LundiP1'=> false,
                'LundiP2'=> false,
                'LundiP3'=> false,
                'LundiP4'=> false,
                'LundiP5'=> false,
                'LundiP6'=> false,
                'LundiP7'=> false,
                'LundiP8'=> false,
                'LundiP9'=> false,
                'LundiP10'=> false,

                'MardiP1'=> false,
                'MardiP2'=> false,
                'MardiP3'=> false,
                'MardiP4'=> false,
                'MardiP5'=> false,
                'MardiP6'=> false,
                'MardiP7'=> false,
                'MardiP8'=> false,
                'MardiP9'=> false,
                'MardiP10'=> false,

                'MercrediP1'=> false,
                'MercrediP2'=> false,
                'MercrediP3'=> false,
                'MercrediP4'=> false,
                'MercrediP5'=> false,
                'MercrediP6'=> false,
                'MercrediP7'=> false,
                'MercrediP8'=> false,
                'MercrediP9'=> false,
                'MercrediP10'=> false,

                'JeudiP1'=> false,
                'JeudiP2'=> false,
                'JeudiP3'=> false,
                'JeudiP4'=> false,
                'JeudiP5'=> false,
                'JeudiP6'=> false,
                'JeudiP7'=> false,
                'JeudiP8'=> false,
                'JeudiP9'=> false,
                'JeudiP10'=> false,
                
                'VendrediP1'=> false,
                'VendrediP2'=> false,
                'VendrediP3'=> false,
                'VendrediP4'=> false,
                'VendrediP5'=> false,
                'VendrediP6'=> false,
                'VendrediP7'=> false,
                'VendrediP8'=> false,
                'VendrediP9'=> false,
                'VendrediP10'=> false,
            ],
            [
                'id'=> 4,
                'LundiP1'=> false,
                'LundiP2'=> false,
                'LundiP3'=> false,
                'LundiP4'=> false,
                'LundiP5'=> false,
                'LundiP6'=> false,
                'LundiP7'=> false,
                'LundiP8'=> false,
                'LundiP9'=> false,
                'LundiP10'=> false,

                'MardiP1'=> false,
                'MardiP2'=> false,
                'MardiP3'=> false,
                'MardiP4'=> false,
                'MardiP5'=> false,
                'MardiP6'=> false,
                'MardiP7'=> false,
                'MardiP8'=> false,
                'MardiP9'=> false,
                'MardiP10'=> false,

                'MercrediP1'=> false,
                'MercrediP2'=> false,
                'MercrediP3'=> false,
                'MercrediP4'=> false,
                'MercrediP5'=> false,
                'MercrediP6'=> false,
                'MercrediP7'=> false,
                'MercrediP8'=> false,
                'MercrediP9'=> false,
                'MercrediP10'=> false,

                'JeudiP1'=> false,
                'JeudiP2'=> false,
                'JeudiP3'=> false,
                'JeudiP4'=> false,
                'JeudiP5'=> false,
                'JeudiP6'=> false,
                'JeudiP7'=> false,
                'JeudiP8'=> false,
                'JeudiP9'=> false,
                'JeudiP10'=> false,
                
                'VendrediP1'=> false,
                'VendrediP2'=> false,
                'VendrediP3'=> false,
                'VendrediP4'=> false,
                'VendrediP5'=> false,
                'VendrediP6'=> false,
                'VendrediP7'=> false,
                'VendrediP8'=> false,
                'VendrediP9'=> false,
                'VendrediP10'=> false,
            ],
            [
                'id'=> 5,
                'LundiP1'=> false,
                'LundiP2'=> false,
                'LundiP3'=> false,
                'LundiP4'=> false,
                'LundiP5'=> false,
                'LundiP6'=> false,
                'LundiP7'=> false,
                'LundiP8'=> false,
                'LundiP9'=> false,
                'LundiP10'=> false,

                'MardiP1'=> false,
                'MardiP2'=> false,
                'MardiP3'=> false,
                'MardiP4'=> false,
                'MardiP5'=> false,
                'MardiP6'=> false,
                'MardiP7'=> false,
                'MardiP8'=> false,
                'MardiP9'=> false,
                'MardiP10'=> false,

                'MercrediP1'=> false,
                'MercrediP2'=> false,
                'MercrediP3'=> false,
                'MercrediP4'=> false,
                'MercrediP5'=> false,
                'MercrediP6'=> false,
                'MercrediP7'=> false,
                'MercrediP8'=> false,
                'MercrediP9'=> false,
                'MercrediP10'=> false,

                'JeudiP1'=> false,
                'JeudiP2'=> false,
                'JeudiP3'=> false,
                'JeudiP4'=> false,
                'JeudiP5'=> false,
                'JeudiP6'=> false,
                'JeudiP7'=> false,
                'JeudiP8'=> false,
                'JeudiP9'=> false,
                'JeudiP10'=> false,
                
                'VendrediP1'=> false,
                'VendrediP2'=> false,
                'VendrediP3'=> false,
                'VendrediP4'=> false,
                'VendrediP5'=> false,
                'VendrediP6'=> false,
                'VendrediP7'=> false,
                'VendrediP8'=> false,
                'VendrediP9'=> false,
                'VendrediP10'=> false,
            ],
            [
                'id'=> 6,
                'LundiP1'=> false,
                'LundiP2'=> false,
                'LundiP3'=> false,
                'LundiP4'=> false,
                'LundiP5'=> false,
                'LundiP6'=> false,
                'LundiP7'=> false,
                'LundiP8'=> false,
                'LundiP9'=> false,
                'LundiP10'=> false,

                'MardiP1'=> false,
                'MardiP2'=> false,
                'MardiP3'=> false,
                'MardiP4'=> false,
                'MardiP5'=> false,
                'MardiP6'=> false,
                'MardiP7'=> false,
                'MardiP8'=> false,
                'MardiP9'=> false,
                'MardiP10'=> false,

                'MercrediP1'=> false,
                'MercrediP2'=> false,
                'MercrediP3'=> false,
                'MercrediP4'=> false,
                'MercrediP5'=> false,
                'MercrediP6'=> false,
                'MercrediP7'=> false,
                'MercrediP8'=> false,
                'MercrediP9'=> false,
                'MercrediP10'=> false,

                'JeudiP1'=> false,
                'JeudiP2'=> false,
                'JeudiP3'=> false,
                'JeudiP4'=> false,
                'JeudiP5'=> false,
                'JeudiP6'=> false,
                'JeudiP7'=> false,
                'JeudiP8'=> false,
                'JeudiP9'=> false,
                'JeudiP10'=> false,
                
                'VendrediP1'=> false,
                'VendrediP2'=> false,
                'VendrediP3'=> false,
                'VendrediP4'=> false,
                'VendrediP5'=> false,
                'VendrediP6'=> false,
                'VendrediP7'=> false,
                'VendrediP8'=> false,
                'VendrediP9'=> false,
                'VendrediP10'=> false,
            ],
            [
                'id'=> 7,
                'LundiP1'=> false,
                'LundiP2'=> false,
                'LundiP3'=> false,
                'LundiP4'=> false,
                'LundiP5'=> false,
                'LundiP6'=> false,
                'LundiP7'=> false,
                'LundiP8'=> false,
                'LundiP9'=> false,
                'LundiP10'=> false,

                'MardiP1'=> false,
                'MardiP2'=> false,
                'MardiP3'=> false,
                'MardiP4'=> false,
                'MardiP5'=> false,
                'MardiP6'=> false,
                'MardiP7'=> false,
                'MardiP8'=> false,
                'MardiP9'=> false,
                'MardiP10'=> false,

                'MercrediP1'=> false,
                'MercrediP2'=> false,
                'MercrediP3'=> false,
                'MercrediP4'=> false,
                'MercrediP5'=> false,
                'MercrediP6'=> false,
                'MercrediP7'=> false,
                'MercrediP8'=> false,
                'MercrediP9'=> false,
                'MercrediP10'=> false,

                'JeudiP1'=> false,
                'JeudiP2'=> false,
                'JeudiP3'=> false,
                'JeudiP4'=> false,
                'JeudiP5'=> false,
                'JeudiP6'=> false,
                'JeudiP7'=> false,
                'JeudiP8'=> false,
                'JeudiP9'=> false,
                'JeudiP10'=> false,
                
                'VendrediP1'=> false,
                'VendrediP2'=> false,
                'VendrediP3'=> false,
                'VendrediP4'=> false,
                'VendrediP5'=> false,
                'VendrediP6'=> false,
                'VendrediP7'=> false,
                'VendrediP8'=> false,
                'VendrediP9'=> false,
                'VendrediP10'=> false,
            ],
            [
                'id'=> 8,
                'LundiP1'=> false,
                'LundiP2'=> false,
                'LundiP3'=> false,
                'LundiP4'=> false,
                'LundiP5'=> false,
                'LundiP6'=> false,
                'LundiP7'=> false,
                'LundiP8'=> false,
                'LundiP9'=> false,
                'LundiP10'=> false,

                'MardiP1'=> false,
                'MardiP2'=> false,
                'MardiP3'=> false,
                'MardiP4'=> false,
                'MardiP5'=> false,
                'MardiP6'=> false,
                'MardiP7'=> false,
                'MardiP8'=> false,
                'MardiP9'=> false,
                'MardiP10'=> false,

                'MercrediP1'=> false,
                'MercrediP2'=> false,
                'MercrediP3'=> false,
                'MercrediP4'=> false,
                'MercrediP5'=> false,
                'MercrediP6'=> false,
                'MercrediP7'=> false,
                'MercrediP8'=> false,
                'MercrediP9'=> false,
                'MercrediP10'=> false,

                'JeudiP1'=> false,
                'JeudiP2'=> false,
                'JeudiP3'=> false,
                'JeudiP4'=> false,
                'JeudiP5'=> false,
                'JeudiP6'=> false,
                'JeudiP7'=> false,
                'JeudiP8'=> false,
                'JeudiP9'=> false,
                'JeudiP10'=> false,
                
                'VendrediP1'=> false,
                'VendrediP2'=> false,
                'VendrediP3'=> false,
                'VendrediP4'=> false,
                'VendrediP5'=> false,
                'VendrediP6'=> false,
                'VendrediP7'=> false,
                'VendrediP8'=> false,
                'VendrediP9'=> false,
                'VendrediP10'=> false,
            ],
            
        ]);
    }
}
