<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CalendrierNotesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('calendriernotes')->insert([
            [
                'id'=> 1,

                'LundiP1'=> 'cours',
                'LundiP2'=> 'cours',
                'LundiP3'=> 'cours',
                'LundiP4'=> 'cours',
                'LundiP5'=> 'cours',
                'LundiP6'=> 'cours',
                'LundiP7'=> 'cours',
                'LundiP8'=> 'cours',
                'LundiP9'=> 'cours',
                'LundiP10'=> 'cours',

                'MardiP1'=> 'cours',
                'MardiP2'=> 'cours',
                'MardiP3'=> 'cours',
                'MardiP4'=> 'cours',
                'MardiP5'=> 'cours',
                'MardiP6'=> 'cours',
                'MardiP7'=> 'cours',
                'MardiP8'=> 'cours',
                'MardiP9'=> 'cours',
                'MardiP10'=> 'cours',

                'MercrediP1'=> 'cours',
                'MercrediP2'=> 'cours',
                'MercrediP3'=> 'cours',
                'MercrediP4'=> 'cours',
                'MercrediP5'=> 'cours',
                'MercrediP6'=> 'cours',
                'MercrediP7'=> 'cours',
                'MercrediP8'=> 'cours',
                'MercrediP9'=> 'cours',
                'MercrediP10'=> 'cours',

                'JeudiP1'=> 'cours',
                'JeudiP2'=> 'cours',
                'JeudiP3'=> 'cours',
                'JeudiP4'=> 'cours',
                'JeudiP5'=> 'cours',
                'JeudiP6'=> 'cours',
                'JeudiP7'=> 'cours',
                'JeudiP8'=> 'cours',
                'JeudiP9'=> 'cours',
                'JeudiP10'=> 'cours',
                
                'VendrediP1'=> 'cours',
                'VendrediP2'=> 'cours',
                'VendrediP3'=> 'cours',
                'VendrediP4'=> 'cours',
                'VendrediP5'=> 'cours',
                'VendrediP6'=> 'cours',
                'VendrediP7'=> 'cours',
                'VendrediP8'=> 'cours',
                'VendrediP9'=> 'cours',
                'VendrediP10'=> 'cours',
            ],
            [
                'id'=> 2,

                'LundiP1'=> '',
                'LundiP2'=> '',
                'LundiP3'=> '',
                'LundiP4'=> '',
                'LundiP5'=> '',
                'LundiP6'=> '',
                'LundiP7'=> '',
                'LundiP8'=> '',
                'LundiP9'=> '',
                'LundiP10'=> '',

                'MardiP1'=> '',
                'MardiP2'=> '',
                'MardiP3'=> '',
                'MardiP4'=> '',
                'MardiP5'=> '',
                'MardiP6'=> '',
                'MardiP7'=> '',
                'MardiP8'=> '',
                'MardiP9'=> '',
                'MardiP10'=> '',

                'MercrediP1'=> '',
                'MercrediP2'=> '',
                'MercrediP3'=> '',
                'MercrediP4'=> '',
                'MercrediP5'=> '',
                'MercrediP6'=> '',
                'MercrediP7'=> '',
                'MercrediP8'=> '',
                'MercrediP9'=> '',
                'MercrediP10'=> '',

                'JeudiP1'=> '',
                'JeudiP2'=> '',
                'JeudiP3'=> '',
                'JeudiP4'=> '',
                'JeudiP5'=> '',
                'JeudiP6'=> '',
                'JeudiP7'=> '',
                'JeudiP8'=> '',
                'JeudiP9'=> '',
                'JeudiP10'=> '',
                
                'VendrediP1'=> '',
                'VendrediP2'=> '',
                'VendrediP3'=> '',
                'VendrediP4'=> '',
                'VendrediP5'=> '',
                'VendrediP6'=> '',
                'VendrediP7'=> '',
                'VendrediP8'=> '',
                'VendrediP9'=> '',
                'VendrediP10'=> '',
            ],
            [
                'id'=> 3,

                'LundiP1'=> '',
                'LundiP2'=> '',
                'LundiP3'=> '',
                'LundiP4'=> '',
                'LundiP5'=> '',
                'LundiP6'=> '',
                'LundiP7'=> '',
                'LundiP8'=> '',
                'LundiP9'=> '',
                'LundiP10'=> '',

                'MardiP1'=> '',
                'MardiP2'=> '',
                'MardiP3'=> '',
                'MardiP4'=> '',
                'MardiP5'=> '',
                'MardiP6'=> '',
                'MardiP7'=> '',
                'MardiP8'=> '',
                'MardiP9'=> '',
                'MardiP10'=> '',

                'MercrediP1'=> '',
                'MercrediP2'=> '',
                'MercrediP3'=> '',
                'MercrediP4'=> '',
                'MercrediP5'=> '',
                'MercrediP6'=> '',
                'MercrediP7'=> '',
                'MercrediP8'=> '',
                'MercrediP9'=> '',
                'MercrediP10'=> '',

                'JeudiP1'=> '',
                'JeudiP2'=> '',
                'JeudiP3'=> '',
                'JeudiP4'=> '',
                'JeudiP5'=> '',
                'JeudiP6'=> '',
                'JeudiP7'=> '',
                'JeudiP8'=> '',
                'JeudiP9'=> '',
                'JeudiP10'=> '',
                
                'VendrediP1'=> '',
                'VendrediP2'=> '',
                'VendrediP3'=> '',
                'VendrediP4'=> '',
                'VendrediP5'=> '',
                'VendrediP6'=> '',
                'VendrediP7'=> '',
                'VendrediP8'=> '',
                'VendrediP9'=> '',
                'VendrediP10'=> '',
            ],
            [
                'id'=> 4,

                'LundiP1'=> '',
                'LundiP2'=> 'Génie Logiciel',
                'LundiP3'=> 'Génie Logiciel',
                'LundiP4'=> 'Génie Logiciel',
                'LundiP5'=> '',
                'LundiP6'=> 'Calcul 1',
                'LundiP7'=> 'Calcul 1',
                'LundiP8'=> 'Prog Jeu Video',
                'LundiP9'=> 'Prog Jeu Video',
                'LundiP10'=> 'Prog Jeu Video',

                'MardiP1'=> 'Calcul 1',
                'MardiP2'=> '',
                'MardiP3'=> '',
                'MardiP4'=> '',
                'MardiP5'=> 'BD2',
                'MardiP6'=> 'BD2',
                'MardiP7'=> 'BD2',
                'MardiP8'=> '',
                'MardiP9'=> 'Français 4',
                'MardiP10'=> 'Français 4',

                'MercrediP1'=> 'AQL',
                'MercrediP2'=> 'AQL',
                'MercrediP3'=> 'AQL',
                'MercrediP4'=> 'AQL',
                'MercrediP5'=> 'Prog Jeu Video',
                'MercrediP6'=> 'Prog Jeu Video',
                'MercrediP7'=> 'Génie Logiciel',
                'MercrediP8'=> 'Génie Logiciel',
                'MercrediP9'=> 'Génie Logiciel',
                'MercrediP10'=> 'Génie Logiciel',

                'JeudiP1'=> 'BD2',
                'JeudiP2'=> 'BD2',
                'JeudiP3'=> 'BD2',
                'JeudiP4'=> 'ATE',
                'JeudiP5'=> '',
                'JeudiP6'=> '',
                'JeudiP7'=> '',
                'JeudiP8'=> 'Français 4',
                'JeudiP9'=> 'Français 4',
                'JeudiP10'=> '',
                
                'VendrediP1'=> '',
                'VendrediP2'=> '',
                'VendrediP3'=> 'Calcul 1',
                'VendrediP4'=> 'Calcul 1',
                'VendrediP5'=> '',
                'VendrediP6'=> '',
                'VendrediP7'=> '',
                'VendrediP8'=> '',
                'VendrediP9'=> '',
                'VendrediP10'=> '',
            ],
            [
                'id'=> 5,

                'LundiP1'=> '',
                'LundiP2'=> '',
                'LundiP3'=> '',
                'LundiP4'=> '',
                'LundiP5'=> '',
                'LundiP6'=> '',
                'LundiP7'=> '',
                'LundiP8'=> '',
                'LundiP9'=> '',
                'LundiP10'=> '',

                'MardiP1'=> '',
                'MardiP2'=> '',
                'MardiP3'=> '',
                'MardiP4'=> '',
                'MardiP5'=> '',
                'MardiP6'=> '',
                'MardiP7'=> '',
                'MardiP8'=> '',
                'MardiP9'=> '',
                'MardiP10'=> '',

                'MercrediP1'=> '',
                'MercrediP2'=> '',
                'MercrediP3'=> '',
                'MercrediP4'=> '',
                'MercrediP5'=> '',
                'MercrediP6'=> '',
                'MercrediP7'=> '',
                'MercrediP8'=> '',
                'MercrediP9'=> '',
                'MercrediP10'=> '',

                'JeudiP1'=> '',
                'JeudiP2'=> '',
                'JeudiP3'=> '',
                'JeudiP4'=> '',
                'JeudiP5'=> '',
                'JeudiP6'=> '',
                'JeudiP7'=> '',
                'JeudiP8'=> '',
                'JeudiP9'=> '',
                'JeudiP10'=> '',
                
                'VendrediP1'=> '',
                'VendrediP2'=> '',
                'VendrediP3'=> '',
                'VendrediP4'=> '',
                'VendrediP5'=> '',
                'VendrediP6'=> '',
                'VendrediP7'=> '',
                'VendrediP8'=> '',
                'VendrediP9'=> '',
                'VendrediP10'=> '',
            ],
            [
                'id'=> 6,

                'LundiP1'=> '',
                'LundiP2'=> '',
                'LundiP3'=> '',
                'LundiP4'=> '',
                'LundiP5'=> '',
                'LundiP6'=> '',
                'LundiP7'=> '',
                'LundiP8'=> '',
                'LundiP9'=> '',
                'LundiP10'=> '',

                'MardiP1'=> '',
                'MardiP2'=> '',
                'MardiP3'=> '',
                'MardiP4'=> '',
                'MardiP5'=> '',
                'MardiP6'=> '',
                'MardiP7'=> '',
                'MardiP8'=> '',
                'MardiP9'=> '',
                'MardiP10'=> '',

                'MercrediP1'=> '',
                'MercrediP2'=> '',
                'MercrediP3'=> '',
                'MercrediP4'=> '',
                'MercrediP5'=> '',
                'MercrediP6'=> '',
                'MercrediP7'=> '',
                'MercrediP8'=> '',
                'MercrediP9'=> '',
                'MercrediP10'=> '',

                'JeudiP1'=> '',
                'JeudiP2'=> '',
                'JeudiP3'=> '',
                'JeudiP4'=> '',
                'JeudiP5'=> '',
                'JeudiP6'=> '',
                'JeudiP7'=> '',
                'JeudiP8'=> '',
                'JeudiP9'=> '',
                'JeudiP10'=> '',
                
                'VendrediP1'=> '',
                'VendrediP2'=> '',
                'VendrediP3'=> '',
                'VendrediP4'=> '',
                'VendrediP5'=> '',
                'VendrediP6'=> '',
                'VendrediP7'=> '',
                'VendrediP8'=> '',
                'VendrediP9'=> '',
                'VendrediP10'=> '',
            ],
            [
                'id'=> 7,

                'LundiP1'=> '',
                'LundiP2'=> '',
                'LundiP3'=> '',
                'LundiP4'=> '',
                'LundiP5'=> '',
                'LundiP6'=> '',
                'LundiP7'=> '',
                'LundiP8'=> '',
                'LundiP9'=> '',
                'LundiP10'=> '',

                'MardiP1'=> '',
                'MardiP2'=> '',
                'MardiP3'=> '',
                'MardiP4'=> '',
                'MardiP5'=> '',
                'MardiP6'=> '',
                'MardiP7'=> '',
                'MardiP8'=> '',
                'MardiP9'=> '',
                'MardiP10'=> '',

                'MercrediP1'=> '',
                'MercrediP2'=> '',
                'MercrediP3'=> '',
                'MercrediP4'=> '',
                'MercrediP5'=> '',
                'MercrediP6'=> '',
                'MercrediP7'=> '',
                'MercrediP8'=> '',
                'MercrediP9'=> '',
                'MercrediP10'=> '',

                'JeudiP1'=> '',
                'JeudiP2'=> '',
                'JeudiP3'=> '',
                'JeudiP4'=> '',
                'JeudiP5'=> '',
                'JeudiP6'=> '',
                'JeudiP7'=> '',
                'JeudiP8'=> '',
                'JeudiP9'=> '',
                'JeudiP10'=> '',
                
                'VendrediP1'=> '',
                'VendrediP2'=> '',
                'VendrediP3'=> '',
                'VendrediP4'=> '',
                'VendrediP5'=> '',
                'VendrediP6'=> '',
                'VendrediP7'=> '',
                'VendrediP8'=> '',
                'VendrediP9'=> '',
                'VendrediP10'=> '',
            ],
            [
                'id'=> 8,

                'LundiP1'=> '',
                'LundiP2'=> '',
                'LundiP3'=> '',
                'LundiP4'=> '',
                'LundiP5'=> '',
                'LundiP6'=> '',
                'LundiP7'=> '',
                'LundiP8'=> '',
                'LundiP9'=> '',
                'LundiP10'=> '',

                'MardiP1'=> '',
                'MardiP2'=> '',
                'MardiP3'=> '',
                'MardiP4'=> '',
                'MardiP5'=> '',
                'MardiP6'=> '',
                'MardiP7'=> '',
                'MardiP8'=> '',
                'MardiP9'=> '',
                'MardiP10'=> '',

                'MercrediP1'=> '',
                'MercrediP2'=> '',
                'MercrediP3'=> '',
                'MercrediP4'=> '',
                'MercrediP5'=> '',
                'MercrediP6'=> '',
                'MercrediP7'=> '',
                'MercrediP8'=> '',
                'MercrediP9'=> '',
                'MercrediP10'=> '',

                'JeudiP1'=> '',
                'JeudiP2'=> '',
                'JeudiP3'=> '',
                'JeudiP4'=> '',
                'JeudiP5'=> '',
                'JeudiP6'=> '',
                'JeudiP7'=> '',
                'JeudiP8'=> '',
                'JeudiP9'=> '',
                'JeudiP10'=> '',
                
                'VendrediP1'=> '',
                'VendrediP2'=> '',
                'VendrediP3'=> '',
                'VendrediP4'=> '',
                'VendrediP5'=> '',
                'VendrediP6'=> '',
                'VendrediP7'=> '',
                'VendrediP8'=> '',
                'VendrediP9'=> '',
                'VendrediP10'=> '',
            ],
            
        ]);
    }
}
